version: '3'

services:
  jobs-app:
    build: ./jobs/.
    ports:
      - 3010:3010
    environment:
      - MONGO_URI=mongodb://jobs-db:27017/wttw
      - APPLICATION_ENDPOINT=http://localhost:3011
    depends_on:
      rabbitmq:
        condition: service_healthy
  applications-app:
    build: ./applications/.
    environment:
      - MONGO_URI=mongodb://applications-db:27017/wttw
    depends_on:
      rabbitmq:
        condition: service_healthy
  jobs-db:
    image: mongo
  applications-db:
    image: mongo
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  nginx:
    build:
      context : ./nginx/
    ports:
      - 3011:3011
    command: sh -c "/wait && nginx -g \"daemon off;\""
    environment:
      - WAIT_HOSTS=mono-app_applications-app_1:3010,mono-app_applications-app_2:3010,mono-app_applications-app_3:3010
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=5
